name: "Nix CI"
on:
  push:
    branch:
      - main
jobs:
  build-systems:
    strategy:
      matrix:
        package:
          - 'nixosConfigurations.clevo.config.system.build.toplevel'
          # - 'homeConfigurations."grizz@clevo".activationPackage'

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v27
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - uses: cachix/cachix-action@v14
      with:
        name: grizzlt
        # If you chose API tokens for write access OR if you have a private cache
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build '.#${{ matrix.package }}' -L --accept-flake-config
